exports.PER_MINUTE_REQUEST_LIMIT = 100;
exports.PAGINATION_LIMIT = 10;

exports.USER_FIRST_NAME_MAX_LENGTH = 100;
exports.USER_LAST_NAME_MAX_LENGTH = 100;
exports.USER_EMAIL_MAX_LENGTH = 100;
exports.USER_PASSWORD_MIN_LENGTH = 6;
exports.USER_PASSWORD_MAX_LENGTH = 200;

exports.QUIZ_TITLE_MAX_LENGTH = 100;
exports.QUIZ_DESCRIPTION_MAX_LENGTH = 400;
exports.QUIZ_MAX_TAG_LENGTH = 20;
exports.QUIZ_MAX_TAGS = 10;

exports.QUESTION_ID_MAX_LENGTH = 6;
exports.QUESTION_DESCRIPTION_MAX_LENGTH = 1000;

exports.OPTION_ID_MAX_LENGTH = 6;
exports.OPTION_DESCRIPTION_MAX_LENGTH = 400;

exports.IMAGE_URL_MAX_LENGTH = 400;
